In [8]:
# !는 리눅스 명령어 실행해주는 것
! conda install -y seaborn

Solving environment: done

## Package Plan ##

  environment location: /home/piai/anaconda3/envs/dayoni

  added / updated specs:
    - seaborn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandas-1.3.4               |   py38h8c16a72_0         9.6 MB
    pytz-2021.3                |     pyhd3eb1b0_0         171 KB
    seaborn-0.11.2             |     pyhd3eb1b0_0         218 KB
    ------------------------------------------------------------
                                           Total:        10.0 MB

The following NEW packages will be INSTALLED:

  bottleneck         pkgs/main/linux-64::bottleneck-1.3.2-py38heb32a55_1
  numexpr            pkgs/main/linux-64::numexpr-2.7.3-py38h22e1b3c_1
  pandas             pkgs/main/linux-64::pandas-1.3.4-py38h8c16a72_0
  pytz               pkgs/main/noarch::pytz-2021.3-pyhd3eb1b0_0
  seaborn            pkgs/main/noarch::seaborn-0.11.2-pyhd3eb

In [1]:
import torch
import numpy as np
import sklearn
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
# 해당되는 코드에 연결되어 있는 설명(type, parameter, return ***)
?torch.tensor

In [3]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float, requires_grad=True)
# gra는 전파가 안되지만 메모리는 공유하는 복사, 수정 시 연동
b = a.detach()
# 메모리 공유하지 않는 복사, 수정 시 변동X
c = a.clone()

print(a)
print(b)
print(c,'\n')

b[0][0] = 9
print(a)
c[0][0] = 100
print(a)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], grad_fn=<CloneBackward0>) 

tensor([[9., 2.],
        [3., 4.]], requires_grad=True)
tensor([[9., 2.],
        [3., 4.]], requires_grad=True)


In [8]:
#
!nvidia-smi

Mon Nov 22 10:41:25 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.00    Driver Version: 470.82.00    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:17:00.0 Off |                  N/A |
| 18%   43C    P8     7W / 215W |   1062MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:B3:00.0  On |                  N/A |
| 18%   

In [5]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
f = a.to(dtype=torch.int, device=device)
f[0][1] = 9
a, f, device

(tensor([[9., 2.],
         [3., 4.]], requires_grad=True),
 tensor([[9, 9],
         [3, 4]], device='cuda:0', dtype=torch.int32),
 device(type='cuda', index=0))

In [6]:
if torch.cuda.is_available():
    print('cuda index : ', torch.cuda.current_device())
    print('GPU 개수 : ', torch.cuda.device_count())
    print('graphic name : ', torch.cuda.get_device_name())

cuda index :  0
GPU 개수 :  2
graphic name :  NVIDIA GeForce RTX 2080


In [9]:
x = torch.tensor(2)
x, x.dim(), x.shape

(tensor(2), 0, torch.Size([]))

In [11]:
x = torch.rand(2)
x, x.dim(), x.shape

(tensor([0.5616, 0.1026]), 1, torch.Size([2]))

In [17]:
x = torch.rand(2, 1)
x, x.dim(), x.shape

(tensor([[0.0550],
         [0.5684]]),
 2,
 torch.Size([2, 1]))

In [12]:
x = torch.rand(2, 3)
x, x.dim(), x.shape

(tensor([[0.7309, 0.6421, 0.7185],
         [0.8638, 0.6484, 0.8275]]),
 2,
 torch.Size([2, 3]))

In [13]:
x = torch.rand(3, 2, 5)
x, x.dim(), x.shape

(tensor([[[0.5477, 0.8217, 0.2457, 0.5115, 0.7602],
          [0.3892, 0.3415, 0.7365, 0.9543, 0.1797]],
 
         [[0.6642, 0.9298, 0.7299, 0.5160, 0.6932],
          [0.0622, 0.9120, 0.2548, 0.2958, 0.0080]],
 
         [[0.8862, 0.0990, 0.0411, 0.6708, 0.4047],
          [0.5754, 0.9137, 0.8400, 0.6248, 0.6852]]]),
 3,
 torch.Size([3, 2, 5]))

In [19]:
x = torch.rand(128, 3, 4, 4)
x.dim(), x.shape

(4, torch.Size([128, 3, 4, 4]))

In [28]:
x = torch.tensor([[1, 1], [1, 1]])
y = torch.unsqueeze(x, 0)
y

tensor([[[1, 1],
         [1, 1]]])

In [29]:
x.dim(), x.shape, y.dim(), y.shape

(2, torch.Size([2, 2]), 3, torch.Size([1, 2, 2]))

# AUTOGRAD
- Gradient method
- chain rule : 미분해서 곱하는 것(?)
- 3Blue1Brown

In [34]:
x = torch.tensor([5., 3., 9., 7.], requires_grad = True)
w = torch.tensor([1., 1., 1., 1.], requires_grad = True)
b = torch.tensor(0., requires_grad = True)

y = sum(x*w) + b
x, w, y

(tensor([5., 3., 9., 7.], requires_grad=True),
 tensor([1., 1., 1., 1.], requires_grad=True),
 tensor(24., grad_fn=<AddBackward0>))

In [35]:
y.backward()
x.grad, w.grad, b.grad

(tensor([1., 1., 1., 1.]), tensor([5., 3., 9., 7.]), tensor(1.))

In [36]:
learning_rate = 0.01
w = w - learning_rate * w.grad
print(w)
z = sum(x*w) + b
z

tensor([0.9500, 0.9700, 0.9100, 0.9300], grad_fn=<SubBackward0>)


tensor(22.3600, grad_fn=<AddBackward0>)